mqtt:
  host: test.mosquitto.org
  port: 1883
  user: ""
  password: ""
  topic_prefix: peleron/garage

stream_modules:
  - name: systemmemory
    module: systemstatus
    monitor: memory_usage
    output_format: usage_percent
#    cleanup: yes  # This optional boolean value sets whether the module's `cleanup()` function will be called when the software exits.

  - name: systemcpu
    module: systemstatus
    monitor: cpu_usage
    output_format: total_usage

  - name: diskspace
    module: systemstatus
    monitor: disk_usage
    output_format: percentage
    partition_path: C

  - name: diskio
    module: systemstatus
    monitor: disk_activity
    output_format: total_bytes

  - name: systemtemperature
    module: systemstatus
    monitor: temperature
    output_format: celsius
    device: coretemp
    label: Physical id 0

  - name: systemuptime
    module: systemstatus
    monitor: uptime
    output_format: minutes

stream_reads:
  - name: memory
    module: systemmemory
    interval: 2 # Stream read polling interval in seconds

  - name: cpu
    module: systemcpu
    interval: 2 # Stream read polling interval in seconds

  - name: filesystemspace
    module: diskspace
    interval: 2 # Stream read polling interval in seconds

  - name: filesystemio
    module: diskio
    interval: 2 # Stream read polling interval in seconds

  - name: cputemperature
    module: systemtemperature
    interval: 2 # Stream read polling interval in seconds

  - name: timesinceboot
    module: systemuptime
    interval: 2 # Stream read polling interval in seconds

logging:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s %(name)s (%(levelname)s): %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
#    file:
#      class: logging.FileHandler
#      level: DEBUG
#      formatter: simple
#      filename: "debug.log"
  loggers:
    mqtt_gpio:
      level: DEBUG
      handlers: [console]
#      handlers: [console, file]
      propagate: yes